
###
GET http://localhost:3000/tasks

###
POST http://localhost:3000/tasks
content-type: application/json

{
    "task": "For the next app I will make sure to create something really functional",
    "completed": 0
}